### ISSUE TITLE
Trouble following along

### ISSUE THREAD

**Issue by wild-kard** [michaeltandy/ubuntu-desktop-22.04-autoinstall#1]
Hi Michael, I'm trying to follow along with your documentation and I'm having trouble.

Perhaps do you have a more step by step breakdown of how you run each script?

Right now I'm testing just running everything as is without any modifications. 

I've first run 
`bash autoinstall-instructions.sh`
but I get a series of errors about missing files and directories

Here is a copy of the terminal when the errors start
`xorriso : FAILURE : Cannot determine attributes of source file '/home/collin/ubuntu-desktop-22.04-autoinstall/desktop-iso/casper/filesystem.manifest' : No such file or directory`
`xorriso : aborting : -abort_on 'FAILURE' encountered 'FAILURE' `
`autoinstall-instructions.sh: line 86: /cdrom/pool/main/l/lin*/*.deb: No such file or directory`
`autoinstall-instructions.sh: line 90: subiquity/TimeZone: No such file or directory`
`autoinstall-instructions.sh: line 91: /snap/subiquity/3359/usr/bin/subiquity-server: No such file or directory`
`autoinstall-instructions.sh: line 92: /snap/subiquity/3359/usr/bin/python3.8: No such file or directory`

...
`autoinstall-instructions.sh: line 96: unexpected EOF while looking for matching `'' `

`autoinstall-instructions.sh: line 100: syntax error: unexpected end of file`

Also, can i still use this new autoinstall feature (since preseed is now deprecated) to automate installing ubuntu desktop on local removable media instead of over cloud architecture? That's basically what I'm trying to accomplish here and I obviously don't have a cloud config in that scenario.

**Comment by michaeltandy** [comment]
Run [make-autoinstall-image.sh](https://github.com/michaeltandy/ubuntu-desktop-22.04-autoinstall/blob/main/make-autoinstall-image.sh) instead. Ignore `autoinstall-instructions.sh` which was just my notes. I've just pushed a change removing that.

**Comment by michaeltandy** [comment]
> Also, can i still use this new autoinstall feature (since preseed is now deprecated) to automate installing ubuntu desktop on local removable media instead of over cloud architecture?

I can take the ISO generated, use `usb-creator-gtk` to load it onto a USB stick, boot a computer from that and it'll perform an unattended installation of Ubuntu desktop. If that's what you mean, then yes.

Of course, I've only tested this on one computer and a VirtualBox VM - if you've got something exotic like needing to install nvidia drivers, I offer no guarantees :)

**Comment by wild-kard** [comment]
@michaeltandy I see thank you for the response! And thanks so much for making this tool open source.

I flashed my usb and ran the installer but I encountered a crash. Working on a second attempt.

**Comment by michaeltandy** [comment]
When I install using USB, the USB stick gets a partition on it called 'writable' which contains a directory with a name like `install-logs-2022-07-29.0` - you'll find a variety of logs inside which might help you figure out what's going on.

**Comment by wild-kard** [comment]
This might seem a silly question but does booting from the usb and running the "install" menu entry perform the installation on the local disk or on the usb itself?

**Comment by michaeltandy** [comment]
Assuming the autoinstall triggers correctly, it'll install to the local disk.

The details depend on [the storage section of user-data](https://github.com/michaeltandy/ubuntu-desktop-22.04-autoinstall/blob/main/user-data#L17), and [according to this documentation](https://ubuntu.com/server/docs/install/autoinstall-reference#storage) it'll install to the largest disk by default. The documentation has other examples, if you want to choose the right disk in a multi-disk system.

**Comment by wild-kard** [comment]
Ah that's probably why I had issues. For whatever reason, I made the wrong assumption that it was going to be installing ubuntu to the usb itself. I'll have to play with params. 

Thanks for the help.

**Comment by michaeltandy** [comment]
If you're experimenting with this stuff, you could consider installing a virtual machine, such as `virtualbox` (it's open source and you can get it via apt-get on ubuntu) - you can generate the ISO then mount it on a virtual machine and boot it, letting you test your ISO without needing to write it to a USB stick.

**Comment by wild-kard** [comment]
I'll be sure to remember that after I fix this computer I just borked!
