### ISSUE TITLE
iso not able to boot

### ISSUE THREAD

**Issue by changchichung** [michaeltandy/ubuntu-desktop-22.04-autoinstall#2]
I update make-autoinstall-image.sh , replace all 22.04.1 to 22.04.3 
then run make-autoinstall-image.sh , here is the link of console log
https://pastebin.com/dnjWvaFY

then I use dd to write ISO to usb flash 
```
sudo dd if=ubuntu-22.04.3-frankeninstaller.iso of=/dev/sda status=progress
4829323776位元組（4.8 GB，4.5 GiB）已複製，371 s，13.0 MB/s
輸入 9443088+0 個紀錄
輸出 9443088+0 個紀錄
4834861056位元組（4.8 GB，4.5 GiB）已複製，381.159 s，12.7 MB/s
```

then I boot from this usb flash , 
I check the BIOS , this flash only show when BIOS is in legacy mode . 
but it's not able to boot .
and if enable EFI , then there's no option to boot from this flash.
that's the first  issue.

so I try to create a VM iwith virtualBOX , then I saw this error
![](https://i.imgur.com/4aR0rDj.png)
and here is the crash log
![](https://i.imgur.com/JqN8kok.png)

any suggestions ?

**Comment by michaeltandy** [comment]
I'll look into it when I have the time.

If you want to get results urgently, I believe you could get the 22.04.1 files from https://old-releases.ubuntu.com/releases/22.04/ if you feel like it.

**Comment by michaeltandy** [comment]
I've updated the script to work with the 22.04.3 ISO.
