### ISSUE TITLE
Open to contract work?

### ISSUE THREAD

**Issue by wild-kard** [michaeltandy/ubuntu-desktop-22.04-autoinstall#4]
Are you open to any kind of contract work on a variation of this installer?

I have need of a very barebones ubuntu desktop autoinstaller and while I am working on my own fork of this codebase, I am willing to pay you for your help on such a variation if you are interested.

**Comment by michaeltandy** [comment]
I'm not looking to take on any extra paid work right now, but if you just need a few pointers feel free to ask.

**Comment by wild-kard** [comment]
I noticed that you used the server iso as the base and then modified the squash file system, I assume so that you could use LUKS encryption?

What I'm trying to build is a minimal ubuntu desktop autoinstaller that I can bake into a larger application. It would be better for my purposes if it didn't use cloud init so I could do it offline. Is this possible?

All I really need it to do is a default install of vanilla 22.04 ubuntu desktop iso with a default user, no root password, no extra partitions, and no disc encryption

Ideally I would like there to be no gnome utility pop up at first boot after install. I'd like to have all of that taken care of by the preseed (user-data file).

I am targeting an ubuntu install that requires no input from the user apart from inserting the installation media and maybe confiruging BIOS boot order, if necessary.

I want them to be able to plug in a usb and end up at a desktop screen with my desktop application running on a newly installed ubuntu desktop installation.

**Comment by wild-kard** [comment]
In theory, all I need to do is crack open a vanilla ubuntu desktop iso, create the nocloud directory with a user-data and a meta-data file and modify my grub.cfg to use autoinstall...and then repackage the iso...right?
